### ISSUE TITLE
Enable caching of compiled ClojureScript to lower initial compilation times

### ISSUE THREAD

**Issue by pandeiro** [adzerk-oss/boot-cljs#22]
Right now, depending on hardware of course, the initial compilation of a ClojureScript app can take anywhere from 15 seconds to multiple minutes.

The Leiningen plugin gets around this (somewhat) because already-compiled portions of the ClojureScript source are not recompiled, even from a fresh `lein cljsbuild once`.

I know Boot has a different philosophy, but is there any workaround possible for this?

**Comment by Deraen** [comment]
If or when boot gets persistent cache dirs, this should be easy to implement.

If there is no cached cljs.core analyze result, it would be generated in pod with only clojurescript dependency.
If there is cached cljs.core analyze result, it would be copied to tempdir and that used as :cache-dir for cljs task.

**Comment by micha** [comment]
See boot-clj/boot@cfb66057b0ae7fd9954fe0d579ea463c6666fd2e

**Comment by lypanov** [comment]
I'm seeing 13-35 second build times even for second build, far above the 1-2 seconds seen with lein. Is this expected and related to this issue or is it a Windows specific performance issue?

**Comment by martinklepsch** [comment]
@lypanov which optimisation mode? With `:none` I get 1s builds on my Mac without the kind of caching described here.

**Comment by lypanov** [comment]
Also using :none. I've added plenty of debugging and see that it's mostly overhead. Some sort of file copying?

**Comment by pandeiro** [comment]
Boot version? I think this was an issue previously with large numbers of static files

**Comment by jeluard** [comment]
I can also see slow recompilation after a simple file `touch`, 10 second vs less than a second with `lein-cljsbuild`. This is with boot `rc9` and latest `boot-cljs`.

**Comment by martinklepsch** [comment]
@jeluard can you gist your `build.boot` file and the first few lines of `boot -h` please?

**Comment by jeluard** [comment]
Here it is:

```
> boot -h
Boot App Version: 2.0.0-rc9
Boot Lib Version: 2.0.0-rc9
Clojure Version:  1.6.0
```

[build.boot](https://gist.github.com/jeluard/57979ab95e9644194965)

**Comment by martinklepsch** [comment]
Can't see anything significantly wrong with your setup.
Are there large number of files in your `:source-paths`/`:resource-paths`? 
Maybe `sift` could be done outside of the `watch` task?
Did you try using `.cljs.edn` files instead of `output-to`?

(I don't see how these things relate to what you're describing but I figured some stabbing in the dark is better than nothing :))

**Comment by jeluard** [comment]
I have definitively more than a couple files but nothing I would consider out of the norm.

`find src -print | wc -l` 103
`find resources -print | wc -l` 48

Removing the `sift` had no significant impact.
I'd rather not use `.cljs.edn` as I plan to move to the official ClojureScript `:main` option.

Hard to say what's going on as compilation time varies a lot. It can be anywhere between 2s for a simple touch to 20s for a simple `cljs` modification (like introducing a white space). Modifying a `cljx` file doesn't seem to introduce latency.

Note that most of the time is spent after `Compiling boot-cljs-project.js...` is printed.

**Comment by lypanov** [comment]
Jeluard are you changing files on which many others depend maybe? Mine is stable now since I moved away from my own fork of boot-cljs to get it working on Windows (new version mostly just works).

If you do want dependencies to not result in rebuilds (in most cases I'm not sure why it's really needed) then you need to add a flag to CLJS (https://github.com/clojure/clojurescript/wiki/Compiler-Options#recompile-dependents)

I'm seeing constant 3-4 s rebuild times when editing a single file (it's a lot less regular when switching from file to file) after the compiler warms up (one rebuild after initial boot start up, as in, second rebuild is 3-4s).

**Comment by jeluard** [comment]
I tried this option but can't really see any effect. Actually I might be close to your numbers taking into account that my machine is not super fast and that the watch trigger is [slowish on osx](https://github.com/boot-clj/boot/issues/55).

Still I get much quicker compilation with the same project and `lein cljsbuild`. Is it something we could improve with latest ClojureScript caching support?

**Comment by lypanov** [comment]
I'd also like to see a 1 second recompile time to be honest but the overall idle CPU save vs cljsbuild  (5% CPU idle on an i5 vs 0% from boot) makes it a no brainer for me as I'm at times battery constrained.

**Comment by Deraen** [comment]
There is work being done on ClojureScript to AOT compile the cljs.core (and even 3rd party libraries): http://dev.clojure.org/jira/browse/CLJS-897
http://dev.clojure.org/jira/browse/CLJS-1067

It might be that we won't need Boot specific solution to this.

**Comment by Deraen** [comment]
Starting from Cljs 3058 cljs.core is aot compiled into the jar.

I think this can be closed.

**Comment by lypanov** [comment]
Maybe I don't really understand how things should work but upgrading to 3058 didn't help. I've since switched away from boot as it's just too much work to get it working what with it's slow compilation times (with straight up CLJS from the new quick start I get 0% CPU usage watch yet 1s compile times) and it's Windows support only makes it more difficult.

**Comment by Deraen** [comment]
This doesn't have anything to do with recompile times. Only the cold compilation (the first compile after starting the boot) can be improved by using recent Cljs.

**Comment by jeluard** [comment]
Maybe we should have a dedicated ticket for the recompilation times? It looks like most people, myself included, are actually discussing recompilation times. This is actually a much bigger burden than initial compilation time for me.

**Comment by Deraen** [comment]
Yes, I think that would be a good idea.

**Comment by lypanov** [comment]
Sorry the lack of cold compile improvement was implied by the first sentence. The latter sentences are just supporting reasons for me skipping on boot/cljs.

**Comment by Deraen** [comment]
This is somewhat fixes by new Cljs.
