### ISSUE TITLE
Compilation fails when .cljs files are available in resource paths

### ISSUE THREAD

**Issue by jeluard** [adzerk-oss/boot-cljs#57]
All `cljs` files found in `:resources-paths` locations will be required in the default `main.cljs.edn`. This can lead to compilation errors as those files are not intended to be compiled.

**Comment by upgradingdave** [comment]
I think I'm running into a similar issue, although I'm just trying boot for the first time, so not sure if it's legal (or makes sense) to set the target output dir to a directory inside `:resource-paths`?

I have this simple directory structure:
        .
        |- .nrepl-port
        |- build.boot
        + resources
          + public
            |- index.html
        + src
          + bootcljs
            |- core.cljs

Here's my build.boot: 

     (set-env!
       :source-paths #{"src"}
       :resource-paths #{"resources"}
       :dependencies 
       '[
         [org.clojure/clojure       "1.6.0"                               ]
         [org.clojure/clojurescript "0.0-3169"                            ]
         [org.clojure/core.async    "0.1.346.0-17112a-alpha"              ]
         [adzerk/boot-cljs          "0.0-2814-3"             :scope "test"]
         [adzerk/boot-cljs-repl     "0.1.9"                  :scope "test"]
         [adzerk/boot-reload        "0.2.6"                  :scope "test"]
         [pandeiro/boot-http        "0.6.2"                  :scope "test"]
         [com.taoensso/timbre       "3.3.1"]
         ])
     
     (require
      '[adzerk.boot-cljs      :refer [cljs]]
      '[adzerk.boot-cljs-repl :refer [cljs-repl start-repl]]
      '[adzerk.boot-reload    :refer [reload]]
      '[pandeiro.boot-http    :refer [serve]])
       
I'd like to compile cljs into `resources/public`. When I run this: 

     boot -t resources/public cljs -sO none

I end up with this (notice that it moved `index.html` into `resources/public/public`:

      .
      |- .nrepl-port
      |- build.boot
      + resources
        + public
          |- boot-cljs-main.js
          |- main.js
          + out
            + boot
              + cljs
                |- main.cljs
                |- main.cljs.cache.edn
                |- main.js
                |- main.js.map
            + bootcljs
              |- core.cljs
              |- core.cljs.cache.edn
              |- core.js
              |- core.js.map
            + cljs
            + clojure
            + goog
            + taoensso
          + public
            |- index.html
      + src
        + bootcljs
          |- core.cljs

If I add a `watch` task, then it appears to continuously recompile cljs found under `resources` and continuously adds "public" folders deeper and deeper until a stack overflow.

**Comment by alandipert** [comment]
@upgradingdave not to harsh your vibes too much, but that's not a great idea :-)

Boot builds are pipelines through which a value, the "[fileset](https://github.com/boot-clj/boot/wiki/Filesets)", is threaded.  At the end of the build pipeline, the fileset value is synchronized to disk (the target/ directory by default).

The synchronization blows away anything in target/ that's not also in the fileset.

Am I correct in understanding that you just want to accumulate all of your assets, including your compiled cljs, into a directory you can serve?

If so, then the way to consider the problem is one of moving the assets you want to end up in target/ through the build pipeline.  The pipeline is unidirectional.  I think you're already achieving this because you have them in [resource-paths](https://github.com/boot-clj/boot/wiki/Filesets#fileset-components), and anything in resource-paths will make it through the pipeline unless a task explicitly removes files from the fileset.

**Comment by upgradingdave** [comment]
Laaaight bulb! (channeling my inner Gru from Despicable Me).

Thanks for the explanation, that makes good sense. I'm looking forward to understanding more about how filesets work under the hood. 

And I'm really excited to dig deeper into boot in general, seems like some really refreshing ways to think about tasks normally done in build tools. Very cool stuff. 

Thanks again!
Dave

**Comment by Deraen** [comment]
If I understood correctly, on problem here was trying to use point target dir to resources path.
